// Generated by site-packs.sh from the built data packs. Do not edit by hand.
window.RGEN_PACKS = {
 "prices": {
  "single": {
   "label": "Single pack",
   "price": "$79",
   "period": "per year"
  },
  "all": {
   "label": "All packs",
   "price": "$199",
   "period": "per year"
  }
 },
 "contact": "rodrigo.abt@gmail.com",
 "packs": [
  {
   "name": "fintech",
   "title": "Fintech & Payments",
   "version": "1.0.0",
   "pitch": "Card, bank and ledger data that passes real validators.",
   "bullets": [
    "Luhn-valid test cards for 7 networks in a realistic mix",
    "IBANs for 55 countries with national check digits, plus BIC, US routing numbers and Mexican CLABE",
    "981 merchant category codes with spend categories, merchant names and realistic ticket sizes",
    "Chart of accounts (EN/ES) and journal entries that always balance"
   ],
   "providers": 33,
   "templates": [
    {
     "name": "bank-accounts",
     "description": "Bank accounts across countries: IBAN and BIC for SEPA and others, ABA routing for US, CLABE for Mexico"
    },
    {
     "name": "card-transactions",
     "description": "Customers, cards and card transactions with MCC mix, merchants, amounts, declines and fraud flags"
    },
    {
     "name": "ledger",
     "description": "Double-entry general ledger: chart of accounts and balanced journal entries (debits = credits)"
    },
    {
     "name": "payment-lifecycle",
     "description": "Payment event log: authorized, captured, settled, refunded, disputed, chargeback"
    }
   ],
   "sources": [
    {
     "dataset": "merchant category codes (MCC) and descriptions",
     "source": "mcc-codes by Greg Greenwood, compiled from IRS and USDA public lists",
     "url": "https://github.com/greggles/mcc-codes",
     "license": "The Unlicense (public domain)"
    },
    {
     "dataset": "card networks, IBAN formats, ABA ranges, CLABE bank codes, MCC ranges, spend mix, merchant name patterns, chart of accounts, journal entry types",
     "source": "Cuiq Analytics (curated from public specifications)",
     "url": "https://cuiqanalytics.com/rgen",
     "license": "Proprietary (rgen pack license)"
    }
   ],
   "sample": {
    "columns": [
     "network",
     "card",
     "iban",
     "category",
     "merchant",
     "amount"
    ],
    "rows": [
     [
      "Visa",
      "422466******7889",
      "FR7677336435362399443902649",
      "Books & hobbies",
      "Bennett Booksellers",
      "24.11"
     ],
     [
      "Mastercard",
      "527308******9251",
      "AT337362897859993363",
      "Restaurants",
      "Trattoria Jones",
      "23.29"
     ],
     [
      "Mastercard",
      "535692******6612",
      "BR6026752371081097986015508OT",
      "Restaurants",
      "Evans's Bakehouse",
      "6.81"
     ]
    ]
   }
  },
  {
   "name": "latam",
   "title": "Latin America",
   "version": "1.0.0",
   "pitch": "Latin American people, IDs and places that look local.",
   "bullets": [
    "Chile, Argentina, Mexico, Brazil, Colombia, Peru and Uruguay",
    "RUT, CUIT, CURP, RFC, CPF, CNPJ, NIT, RUC and CI with valid check digits; CURP and RFC built from the person",
    "17,000 population-weighted places with ISO regions, matching postal codes and phone area codes",
    "Local names, banks, company legal forms, plates, and Chilean pensions and health insurers"
   ],
   "providers": 45,
   "templates": [
    {
     "name": "customers",
     "description": "Customers across 7 Latin American countries: local names, national ID, city, region, postal code, phone, email, bank"
    },
    {
     "name": "customers-br",
     "description": "Brazilian customers with CPF, CEP by state, DDD phone and city"
    },
    {
     "name": "customers-mx",
     "description": "Mexican customers with CURP and RFC derived from name and birth date, state, CP and phone"
    },
    {
     "name": "invoices-cl",
     "description": "Chilean companies and electronic tax documents (DTE): facturas, boletas, notas de crédito with IVA 19%"
    },
    {
     "name": "payroll-cl",
     "description": "Chilean payroll: RUT, AFP and health insurer, gross pay, pension (10% + commission), health (7%) and unemployment insurance (0.6%) deductions"
    }
   ],
   "sources": [
    {
     "dataset": "localities, administrative divisions, populations, coordinates",
     "source": "GeoNames",
     "url": "https://www.geonames.org",
     "license": "CC BY 4.0"
    },
    {
     "dataset": "region names, ISO 3166-2 codes, phone area codes, postal rules, given names and surnames, email domains, streets, banks, company styles, Chilean AFP and health providers",
     "source": "Cuiq Analytics (curated from public sources)",
     "url": "https://cuiqanalytics.com/rgen",
     "license": "Proprietary (rgen pack license)"
    }
   ],
   "sample": {
    "columns": [
     "country",
     "name",
     "id",
     "city",
     "postal",
     "mobile"
    ],
    "rows": [
     [
      "PE",
      "José Rojas Vargas",
      "18816188",
      "San Martin, PE-PIU",
      "20599",
      "+51 946 459 284"
     ],
     [
      "MX",
      "José Cruz Álvarez",
      "CUAJ880605HMCRLS60",
      "Tlalnepantla, MX-MEX",
      "52131",
      "+52 722 902 7752"
     ],
     [
      "BR",
      "Ana Pinto Almeida",
      "293.064.652-70",
      "Acará, BR-PA",
      "67704-424",
      "+55 94 97290-3250"
     ]
    ]
   }
  },
  {
   "name": "hr",
   "title": "HR & Workforce",
   "version": "1.0.0",
   "pitch": "Employees, org charts and pay that hang together.",
   "bullets": [
    "1,016 occupations and 54,000 real job titles (O*NET)",
    "Departments, seniority and management ladders, tasks, tech skills and education",
    "Salaries from BLS wage data by occupation, level and US state",
    "Templates: employees, org chart, compensation, recruiting pipeline"
   ],
   "providers": 19,
   "templates": [
    {
     "name": "compensation",
     "description": "Employees with level- and state-adjusted salaries from BLS wage data, plus bonus targets"
    },
    {
     "name": "employees",
     "description": "Employee roster: department, occupation, title, level, skills, education"
    },
    {
     "name": "org-chart",
     "description": "Managers and the employees reporting to them, departments kept consistent"
    },
    {
     "name": "recruiting-pipeline",
     "description": "Candidate funnel event log: applied, screened, interviewing, offer, hired/rejected"
    }
   ],
   "sources": [
    {
     "dataset": "occupations, job titles, tasks, tech skills, knowledge, job zones",
     "source": "O*NET 31.0 Database, U.S. Department of Labor, Employment and Training Administration (USDOL/ETA)",
     "url": "https://www.onetcenter.org/database.html",
     "license": "CC BY 4.0"
    },
    {
     "dataset": "annual wage percentiles by occupation and state (May 2025)",
     "source": "Occupational Employment and Wage Statistics (OEWS), U.S. Bureau of Labor Statistics",
     "url": "https://www.bls.gov/oes/",
     "license": "Public domain (U.S. Government work)"
    },
    {
     "dataset": "departments, department roles and weights, supplemental modern titles, seniority and management ladders, education by job zone",
     "source": "Cuiq Analytics (curated)",
     "url": "https://cuiqanalytics.com/rgen",
     "license": "Proprietary (rgen pack license)"
    }
   ],
   "sample": {
    "columns": [
     "department",
     "job_title",
     "level",
     "state",
     "salary",
     "top_skill"
    ],
    "rows": [
     [
      "Customer Support",
      "Customer Complaints Clerk",
      "Junior",
      "CA",
      "35600.0",
      "GroupMe"
     ],
     [
      "Sales",
      "Outside Sales Representative",
      "Mid-level",
      "OR",
      "75300.0",
      "Microsoft Project"
     ],
     [
      "Engineering",
      "Mobile Engineer",
      "Mid-level",
      "WA",
      "160100.0",
      "LogMeIn GoToMeeting"
     ]
    ]
   }
  },
  {
   "name": "saas-analytics",
   "title": "SaaS & Product Analytics",
   "version": "1.0.0",
   "pitch": "Product analytics data for dashboards, funnels and experiments.",
   "bullets": [
    "Real-looking user agents that parse back to browser, OS and device",
    "Traffic sources with UTM parameters, channels and referrers, including AI assistants",
    "Event taxonomies for B2B SaaS, e-commerce and mobile apps with JSON properties",
    "Plans, seats and MRR; growth-shaped timestamps; funnel, subscription and A/B test templates"
   ],
   "providers": 27,
   "templates": [
    {
     "name": "ab-test",
     "description": "A/B test assignment and outcomes with a built-in 15% relative lift in conversion for treatment"
    },
    {
     "name": "accounts",
     "description": "B2B accounts with industry, size, plan, billing, seats and MRR, plus their users with roles"
    },
    {
     "name": "events",
     "description": "Product event stream (b2b_saas taxonomy): users, growth-shaped timestamps, JSON properties, UTM attribution and parsed user agent"
    },
    {
     "name": "funnel",
     "description": "Visitor-to-paid funnel: traffic source, device and monotonic stage flags/timestamps with channel-dependent conversion"
    },
    {
     "name": "subscriptions",
     "description": "Subscription lifecycle event log: trial, active, past_due, churned, reactivated"
    }
   ],
   "sources": [
    {
     "dataset": "user agent profiles and shares, traffic sources and channels, event taxonomies, plans and prices, account firmographics, time-of-day shapes",
     "source": "Cuiq Analytics (curated; illustrative market defaults)",
     "url": "https://cuiqanalytics.com/rgen",
     "license": "Proprietary (rgen pack license)"
    }
   ],
   "sample": {
    "columns": [
     "source",
     "channel",
     "browser",
     "event",
     "properties"
    ],
    "rows": [
     [
      "hubspot / email",
      "Email",
      "Chrome / Windows / desktop",
      "logged_in",
      "{}"
     ],
     [
      "chatgpt.com / referral",
      "AI Assistants",
      "Safari / iOS / mobile",
      "signed_up",
      "{}"
     ],
     [
      "facebook / paid_social",
      "Paid Social",
      "Chrome / Android / mobile",
      "page_viewed",
      "{\"path\":\"/pricing\",\"load_ms\":411}"
     ]
    ]
   }
  },
  {
   "name": "jobs-pro",
   "title": "Jobs Pro",
   "version": "1.0.0",
   "pitch": "A large custom list of job titles and composable role names.",
   "bullets": [
    "10,000+ curated job titles",
    "Composed titles from seniority/function modifiers and base roles"
   ],
   "providers": 2,
   "templates": [],
   "sources": [
    {
     "dataset": "job titles, job bases, job modifiers",
     "source": "Cuiq Analytics (custom-made)",
     "url": "https://cuiqanalytics.com/rgen",
     "license": "Proprietary (rgen pack license)"
    }
   ],
   "sample": {
    "columns": [
     "title",
     "composed"
    ],
    "rows": [
     [
      "Integrity Assessor",
      "Product Advisor"
     ],
     [
      "Carbider",
      "Equity Activist"
     ],
     [
      "Design Consultant",
      "Chain Worker"
     ]
    ]
   }
  }
 ],
 "providers": [
  {
   "n": "fin_account_code",
   "a": "",
   "d": "chart-of-accounts code",
   "pack": "fintech",
   "s": [
    "6000",
    "6400",
    "6100"
   ],
   "c": "accounting"
  },
  {
   "n": "fin_account_name",
   "a": "acct,locale",
   "d": "account name for a code, locale en or es — dependent: fin_account_name(code)",
   "pack": "fintech",
   "c": "accounting"
  },
  {
   "n": "fin_credit_account",
   "a": "etype",
   "d": "account credited by an entry type — dependent: fin_credit_account(entry_type)",
   "pack": "fintech",
   "c": "accounting"
  },
  {
   "n": "fin_debit_account",
   "a": "etype",
   "d": "account debited by an entry type — dependent: fin_debit_account(entry_type)",
   "pack": "fintech",
   "c": "accounting"
  },
  {
   "n": "fin_entry_amount",
   "a": "etype",
   "d": "amount for a journal entry type (lognormal) — dependent: fin_entry_amount(entry_type)",
   "pack": "fintech",
   "c": "accounting"
  },
  {
   "n": "fin_entry_description",
   "a": "etype,locale",
   "d": "description of a journal entry type, locale en or es — dependent: fin_entry_description(entry_type)",
   "pack": "fintech",
   "c": "accounting"
  },
  {
   "n": "fin_entry_type",
   "a": "",
   "d": "journal entry type (credit_sale, supplier_payment, payroll_accrual, ...) weighted by frequency",
   "pack": "fintech",
   "s": [
    "cogs",
    "cash_receipt",
    "depreciation"
   ],
   "c": "accounting"
  },
  {
   "n": "fin_aba_routing",
   "a": "",
   "d": "US ABA routing number with valid check digit",
   "pack": "fintech",
   "s": [
    "269571765",
    "039351212",
    "693858135"
   ],
   "c": "banking"
  },
  {
   "n": "fin_bic",
   "a": "cc",
   "d": "well-formed BIC/SWIFT code for a country — dependent: fin_bic(country_code)",
   "pack": "fintech",
   "c": "banking"
  },
  {
   "n": "fin_clabe",
   "a": "",
   "d": "Mexican CLABE (18 digits, real bank code, valid check digit)",
   "pack": "fintech",
   "s": [
    "127024485373169864",
    "014390380663655755",
    "638272573067599485"
   ],
   "c": "banking"
  },
  {
   "n": "fin_clabe_bank",
   "a": "clabe",
   "d": "bank name of a CLABE — dependent: fin_clabe_bank(clabe)",
   "pack": "fintech",
   "c": "banking"
  },
  {
   "n": "fin_currency_of",
   "a": "cc",
   "d": "ISO 4217 currency of accounts in an IBAN country (EUR for DE, GBP for GB, ...) — dependent: fin_currency_of(country)",
   "pack": "fintech",
   "c": "banking"
  },
  {
   "n": "fin_iban",
   "a": "",
   "d": "valid IBAN for a random IBAN country, weighted toward SEPA economies",
   "pack": "fintech",
   "s": [
    "GB41PINH11476213992272",
    "SA39736E4OB99FHUYINEVDV9",
    "GR828184955BG7AFR3Y508M6RFS"
   ],
   "c": "banking"
  },
  {
   "n": "fin_iban_country",
   "a": "",
   "d": "country code using IBANs, weighted toward SEPA economies",
   "pack": "fintech",
   "s": [
    "FI",
    "RO",
    "AT"
   ],
   "c": "banking"
  },
  {
   "n": "fin_iban_for",
   "a": "cc",
   "d": "valid IBAN (mod-97 check digits, country BBAN format, national check digits for 17 countries) for a country code column — dependent: fin_iban_for(country)",
   "pack": "fintech",
   "c": "banking"
  },
  {
   "n": "fin_iban_pretty",
   "a": "iban",
   "d": "IBAN printed in groups of four — dependent: fin_iban_pretty(iban)",
   "pack": "fintech",
   "c": "banking"
  },
  {
   "n": "fin_us_account_number",
   "a": "",
   "d": "US bank account number, 8-12 digits",
   "pack": "fintech",
   "s": [
    "67605440",
    "062915994",
    "166292669852"
   ],
   "c": "banking"
  },
  {
   "n": "hr_any_job_title",
   "a": "",
   "d": "job title from 54k real-world titles across all occupations",
   "pack": "hr",
   "s": [
    "Milk Pickup Truck Driver",
    "Sheet Music Salesperson",
    "Call Center Specialist"
   ],
   "c": "hr"
  },
  {
   "n": "hr_candidate_source",
   "a": "",
   "d": "recruiting source of a candidate",
   "pack": "hr",
   "s": [
    "Careers site",
    "Referral",
    "Job board"
   ],
   "c": "hr"
  },
  {
   "n": "hr_department",
   "a": "",
   "d": "company department, weighted by typical headcount share",
   "pack": "hr",
   "s": [
    "Data & Analytics",
    "Marketing",
    "Customer Support"
   ],
   "c": "hr"
  },
  {
   "n": "hr_education",
   "a": "soc",
   "d": "typical education for an occupation — dependent: hr_education(soc_code)",
   "pack": "hr",
   "c": "hr"
  },
  {
   "n": "hr_employment_type",
   "a": "",
   "d": "employment type (Full-time, Part-time, Contractor, Intern)",
   "pack": "hr",
   "s": [
    "Full-time",
    "Full-time",
    "Full-time"
   ],
   "c": "hr"
  },
  {
   "n": "hr_job_title",
   "a": "soc",
   "d": "real-world job title for an occupation code — dependent: hr_job_title(soc_code)",
   "pack": "hr",
   "c": "hr"
  },
  {
   "n": "hr_job_zone",
   "a": "soc",
   "d": "O*NET job zone 1-5 (preparation needed) of an occupation — dependent: hr_job_zone(soc_code)",
   "pack": "hr",
   "c": "hr"
  },
  {
   "n": "hr_knowledge",
   "a": "soc",
   "d": "knowledge area important to an occupation, weighted by importance — dependent: hr_knowledge(soc_code)",
   "pack": "hr",
   "c": "hr"
  },
  {
   "n": "hr_management_level",
   "a": "",
   "d": "management level (Team Lead to C-level), pyramid-shaped mix",
   "pack": "hr",
   "s": [
    "Senior Manager",
    "Director",
    "Team Lead"
   ],
   "c": "hr"
  },
  {
   "n": "hr_manager_soc_code_in",
   "a": "dept",
   "d": "management occupation code for a department — dependent: hr_manager_soc_code_in(department)",
   "pack": "hr",
   "c": "hr"
  },
  {
   "n": "hr_occupation",
   "a": "soc",
   "d": "standard occupation name for an occupation code — dependent: hr_occupation(soc_code)",
   "pack": "hr",
   "c": "hr"
  },
  {
   "n": "hr_salary",
   "a": "soc",
   "d": "annual salary (USD) drawn from the occupation's BLS wage distribution — dependent: hr_salary(soc_code)",
   "pack": "hr",
   "c": "hr"
  },
  {
   "n": "hr_salary_for",
   "a": "soc,lvl",
   "d": "annual salary (USD) for an occupation at a seniority or management level, e.g. hr_salary_for(soc_code, seniority)",
   "pack": "hr",
   "c": "hr"
  },
  {
   "n": "hr_salary_in",
   "a": "soc,lvl,st",
   "d": "annual salary (USD) for an occupation and level, adjusted to a US state, e.g. hr_salary_in(soc_code, seniority, state_code)",
   "pack": "hr",
   "c": "hr"
  },
  {
   "n": "hr_seniority",
   "a": "",
   "d": "individual-contributor level (Intern to Principal), realistic mix",
   "pack": "hr",
   "s": [
    "Mid-level",
    "Mid-level",
    "Senior"
   ],
   "c": "hr"
  },
  {
   "n": "hr_soc_code",
   "a": "",
   "d": "O*NET-SOC occupation code of a typical company role, e.g. 15-1252.00",
   "pack": "hr",
   "s": [
    "27-1024.00",
    "41-3091.00",
    "13-1081.02"
   ],
   "c": "hr"
  },
  {
   "n": "hr_soc_code_in",
   "a": "dept",
   "d": "individual-contributor occupation code in a department, weighted by headcount — dependent: hr_soc_code_in(department)",
   "pack": "hr",
   "c": "hr"
  },
  {
   "n": "hr_task",
   "a": "soc",
   "d": "core work task of an occupation — dependent: hr_task(soc_code)",
   "pack": "hr",
   "c": "hr"
  },
  {
   "n": "hr_tech_skill",
   "a": "soc",
   "d": "software/technology skill used in an occupation, hot technologies favored — dependent: hr_tech_skill(soc_code)",
   "pack": "hr",
   "c": "hr"
  },
  {
   "n": "latam_bank",
   "a": "cc",
   "d": "bank of a country weighted by customer base — dependent: latam_bank(country)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_birthdate",
   "a": "min_age,max_age",
   "d": "birth date for an adult, ages 18-80 by default",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_cedula_co",
   "a": "",
   "d": "Colombian cédula de ciudadanía (8 or 10 digits)",
   "pack": "latam",
   "s": [
    "1056405210",
    "75512906",
    "1120720128"
   ],
   "c": "latam"
  },
  {
   "n": "latam_ci_uy",
   "a": "",
   "d": "Uruguayan cédula de identidad with valid check digit, formatted 1.234.567-8",
   "pack": "latam",
   "s": [
    "1.022.942-4",
    "1.952.674-0",
    "4.520.873-0"
   ],
   "c": "latam"
  },
  {
   "n": "latam_city",
   "a": "pid",
   "d": "city, town or comuna of a place — dependent: latam_city(place_id)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_cl_afp",
   "a": "",
   "d": "Chilean pension fund (AFP) weighted by affiliates",
   "pack": "latam",
   "s": [
    "AFP Modelo",
    "AFP Cuprum",
    "AFP Modelo"
   ],
   "c": "latam"
  },
  {
   "n": "latam_cl_afp_rate",
   "a": "fund",
   "d": "employee pension deduction % (10% + AFP commission, approximate) — dependent: latam_cl_afp_rate(afp)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_cl_health",
   "a": "",
   "d": "Chilean health insurer: Fonasa (about 78%) or an Isapre",
   "pack": "latam",
   "s": [
    "Fonasa",
    "Isapre Nueva Masvida",
    "Fonasa"
   ],
   "c": "latam"
  },
  {
   "n": "latam_cnpj",
   "a": "",
   "d": "Brazilian CNPJ (head office /0001) with valid check digits, formatted 12.345.678/0001-95",
   "pack": "latam",
   "s": [
    "97.043.697/0001-10",
    "69.959.648/0001-96",
    "42.057.022/0001-38"
   ],
   "c": "latam"
  },
  {
   "n": "latam_company",
   "a": "cc",
   "d": "fictional company name with the country's legal form (SpA, S.A. de C.V., Ltda., S.A.S., S.A.C.) — dependent: latam_company(country)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_country",
   "a": "",
   "d": "country code CL, AR, MX, BR, CO, PE or UY, weighted by population",
   "pack": "latam",
   "s": [
    "BR",
    "MX",
    "MX"
   ],
   "c": "latam"
  },
  {
   "n": "latam_country_name",
   "a": "cc",
   "d": "local country name (Brasil, México, Perú, ...) — dependent: latam_country_name(country)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_country_of",
   "a": "pid",
   "d": "country code of a place — dependent: latam_country_of(place_id)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_cpf",
   "a": "",
   "d": "Brazilian CPF with valid check digits, formatted 123.456.789-09",
   "pack": "latam",
   "s": [
    "717.153.222-40",
    "674.373.497-79",
    "287.096.502-88"
   ],
   "c": "latam"
  },
  {
   "n": "latam_cuit",
   "a": "kind,sex",
   "d": "Argentine CUIT/CUIL with valid check digit, 20-12345678-3; kind person (sex F/M) or company",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_curp",
   "a": "given,surname1,surname2,birthdate,sex,pid",
   "d": "Mexican CURP derived from name, birth date, sex F/M and the place's state, valid check digit — dependent: latam_curp(given, surname1, surname2, birthdate, sex, place_id)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_currency",
   "a": "cc",
   "d": "ISO 4217 currency of a country — dependent: latam_currency(country)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_dni_ar",
   "a": "",
   "d": "Argentine DNI, formatted 12.345.678",
   "pack": "latam",
   "s": [
    "27.690.067",
    "14.996.229",
    "43.668.942"
   ],
   "c": "latam"
  },
  {
   "n": "latam_dni_pe",
   "a": "",
   "d": "Peruvian DNI (8 digits)",
   "pack": "latam",
   "s": [
    "52310173",
    "13745955",
    "29617864"
   ],
   "c": "latam"
  },
  {
   "n": "latam_email",
   "a": "given,surname,cc",
   "d": "email from a person's name with the country's common providers — dependent: latam_email(given, surname, country)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_full_name",
   "a": "given,surname1,surname2",
   "d": "full name from given name and one or two surnames — dependent: latam_full_name(given, surname1, surname2)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_given_name",
   "a": "cc,sex",
   "d": "common given name for a country and sex F/M, frequency-weighted — dependent: latam_given_name(country, sex)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_landline",
   "a": "pid",
   "d": "landline number with the area code of the place's region — dependent: latam_landline(place_id)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_lat",
   "a": "pid",
   "d": "latitude near a place — dependent: latam_lat(place_id)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_lon",
   "a": "pid",
   "d": "longitude near a place — dependent: latam_lon(place_id)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_mobile",
   "a": "pid",
   "d": "mobile number in international format with the place's area code where used (AR, BR, MX) — dependent: latam_mobile(place_id)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_national_id",
   "a": "cc",
   "d": "personal ID of a country: RUT, DNI, CURP, CPF, cédula, DNI, CI (use latam_curp for a CURP that matches a person) — dependent: latam_national_id(country)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_nit",
   "a": "",
   "d": "Colombian company NIT with valid verification digit, formatted 900.123.456-7",
   "pack": "latam",
   "s": [
    "916.630.885-7",
    "845.540.071-5",
    "882.544.892-8"
   ],
   "c": "latam"
  },
  {
   "n": "latam_phone_digits",
   "a": "phone",
   "d": "E.164 form of a formatted phone number (+5622345678) — dependent: latam_phone_digits(phone)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_place",
   "a": "cc",
   "d": "population-weighted place id in a country; drives region, city, postal code and phone — dependent: latam_place(country)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_plate",
   "a": "cc",
   "d": "vehicle plate in the country's current formats (CL BCDF12, BR Mercosur ABC1D23, ...) — dependent: latam_plate(country)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_postal_code",
   "a": "pid",
   "d": "postal code consistent with the place's region (BR CEP, MX CP, AR CPA, CO, PE; format-only for CL and UY outside Montevideo) — dependent: latam_postal_code(place_id)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_region",
   "a": "pid",
   "d": "first-level region of a place (región, estado, provincia, departamento, UF) — dependent: latam_region(place_id)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_region_code",
   "a": "pid",
   "d": "ISO 3166-2 code of a place's region, e.g. CL-RM, BR-SP, MX-JAL — dependent: latam_region_code(place_id)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_rfc",
   "a": "given,surname1,surname2,birthdate",
   "d": "Mexican RFC for a person (13 chars) from name and birth date, valid check digit — dependent: latam_rfc(given, surname1, surname2, birthdate)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_rfc_company",
   "a": "",
   "d": "Mexican RFC for a company (12 chars), valid check digit",
   "pack": "latam",
   "s": [
    "MYP061104MU0",
    "TQK9604304V2",
    "FBI031103D81"
   ],
   "c": "latam"
  },
  {
   "n": "latam_ruc_pe",
   "a": "kind",
   "d": "Peruvian RUC (11 digits, 20... companies, 10+DNI persons) with valid check digit",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_rut",
   "a": "kind",
   "d": "Chilean RUT with valid check digit, formatted 12.345.678-5; kind person or company",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_rut_uy",
   "a": "",
   "d": "Uruguayan company RUT (12 digits) with valid check digit",
   "pack": "latam",
   "s": [
    "107931560016",
    "119580090016",
    "107735900012"
   ],
   "c": "latam"
  },
  {
   "n": "latam_second_surname",
   "a": "cc",
   "d": "maternal surname (always in Spanish-speaking countries, half the time in BR) — dependent: latam_second_surname(country)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_sex",
   "a": "",
   "d": "sex F or M (51/49)",
   "pack": "latam",
   "s": [
    "F",
    "F",
    "M"
   ],
   "c": "latam"
  },
  {
   "n": "latam_street_address",
   "a": "cc",
   "d": "street and number written the local way (Calle 45 # 12-34 in CO, Rua ..., 120 in BR) — dependent: latam_street_address(country)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_subregion",
   "a": "pid",
   "d": "second-level unit of a place (provincia, municipio, partido) — dependent: latam_subregion(place_id)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_surname",
   "a": "cc",
   "d": "common surname for a country, frequency-weighted — dependent: latam_surname(country)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "latam_tax_id",
   "a": "cc",
   "d": "company tax ID of a country: RUT, CUIT, RFC, CNPJ, NIT, RUC, RUT — dependent: latam_tax_id(country)",
   "pack": "latam",
   "c": "latam"
  },
  {
   "n": "fin_amount",
   "a": "code",
   "d": "card transaction amount (USD) with a realistic lognormal ticket size for an MCC — dependent: fin_amount(mcc)",
   "pack": "fintech",
   "c": "payments"
  },
  {
   "n": "fin_any_card_number",
   "a": "",
   "d": "Luhn-valid test card number, networks in a US consumer mix",
   "pack": "fintech",
   "s": [
    "6011121287399396",
    "4318584312282173",
    "4936026165759883"
   ],
   "c": "payments"
  },
  {
   "n": "fin_any_mcc",
   "a": "",
   "d": "any of 981 merchant category codes, uniform",
   "pack": "fintech",
   "s": [
    "3088",
    "7276",
    "3260"
   ],
   "c": "payments"
  },
  {
   "n": "fin_auth_code",
   "a": "",
   "d": "6-character authorization code",
   "pack": "fintech",
   "s": [
    "SKRNVJ",
    "IDR752",
    "15FKA9"
   ],
   "c": "payments"
  },
  {
   "n": "fin_card_cvv",
   "a": "net",
   "d": "card security code, 4 digits for American Express — dependent: fin_card_cvv(network)",
   "pack": "fintech",
   "c": "payments"
  },
  {
   "n": "fin_card_expiry",
   "a": "",
   "d": "card expiry MM/YY, 1 to 60 months ahead",
   "pack": "fintech",
   "s": [
    "12/27",
    "08/30",
    "05/31"
   ],
   "c": "payments"
  },
  {
   "n": "fin_card_network",
   "a": "",
   "d": "card network (Visa, Mastercard, American Express, ...), US consumer mix",
   "pack": "fintech",
   "s": [
    "Mastercard",
    "American Express",
    "Visa"
   ],
   "c": "payments"
  },
  {
   "n": "fin_card_network_of",
   "a": "num",
   "d": "card network detected from a card number — dependent: fin_card_network_of(card_number)",
   "pack": "fintech",
   "c": "payments"
  },
  {
   "n": "fin_card_number",
   "a": "net",
   "d": "Luhn-valid test card number for a network column — dependent: fin_card_number(network)",
   "pack": "fintech",
   "c": "payments"
  },
  {
   "n": "fin_decline_reason",
   "a": "",
   "d": "card decline reason, realistic mix",
   "pack": "fintech",
   "s": [
    "Exceeds limit",
    "Insufficient funds",
    "Do not honor"
   ],
   "c": "payments"
  },
  {
   "n": "fin_descriptor",
   "a": "merchant",
   "d": "card statement descriptor, e.g. SQ *GREEN MARKET #0412 — dependent: fin_descriptor(merchant)",
   "pack": "fintech",
   "c": "payments"
  },
  {
   "n": "fin_masked_pan",
   "a": "num",
   "d": "PCI-style masked card number (first 6, last 4) — dependent: fin_masked_pan(card_number)",
   "pack": "fintech",
   "c": "payments"
  },
  {
   "n": "fin_mcc",
   "a": "",
   "d": "merchant category code weighted by consumer card activity",
   "pack": "fintech",
   "s": [
    "5964",
    "5411",
    "5251"
   ],
   "c": "payments"
  },
  {
   "n": "fin_mcc_category",
   "a": "code",
   "d": "spend category of an MCC (Groceries, Restaurants, Fuel, Travel, ...; card-network range name for other codes) — dependent: fin_mcc_category(mcc)",
   "pack": "fintech",
   "c": "payments"
  },
  {
   "n": "fin_mcc_description",
   "a": "code",
   "d": "description of an MCC — dependent: fin_mcc_description(mcc)",
   "pack": "fintech",
   "c": "payments"
  },
  {
   "n": "fin_merchant_name",
   "a": "code",
   "d": "plausible fictional merchant name for an MCC — dependent: fin_merchant_name(mcc)",
   "pack": "fintech",
   "c": "payments"
  },
  {
   "n": "saas_billing_period",
   "a": "pl",
   "d": "billing period monthly or annual (bigger plans bill annually more often), NULL for Free — dependent: saas_billing_period(plan)",
   "pack": "saas-analytics",
   "c": "saas"
  },
  {
   "n": "saas_browser",
   "a": "ua",
   "d": "browser parsed from a user agent (Chrome, Safari, Edge, Firefox, Samsung Internet) — dependent: saas_browser(user_agent)",
   "pack": "saas-analytics",
   "c": "saas"
  },
  {
   "n": "saas_browser_version",
   "a": "ua",
   "d": "major browser version parsed from a user agent — dependent: saas_browser_version(user_agent)",
   "pack": "saas-analytics",
   "c": "saas"
  },
  {
   "n": "saas_channel",
   "a": "tsrc",
   "d": "marketing channel grouping (Organic Search, Paid Social, Email, AI Assistants, ...) — dependent: saas_channel(traffic_source)",
   "pack": "saas-analytics",
   "c": "saas"
  },
  {
   "n": "saas_company_size",
   "a": "",
   "d": "employee-count band (1-10 ... 5000+), SMB-heavy mix",
   "pack": "saas-analytics",
   "s": [
    "1-10",
    "1-10",
    "1-10"
   ],
   "c": "saas"
  },
  {
   "n": "saas_device",
   "a": "ua",
   "d": "device type (desktop, mobile, tablet) parsed from a user agent — dependent: saas_device(user_agent)",
   "pack": "saas-analytics",
   "c": "saas"
  },
  {
   "n": "saas_event",
   "a": "ptype",
   "d": "event name weighted by frequency for a product type: b2b_saas (default), ecommerce or mobile_app",
   "pack": "saas-analytics",
   "c": "saas"
  },
  {
   "n": "saas_event_properties",
   "a": "ev",
   "d": "JSON event properties that fit the event (path for page_viewed, revenue for order_completed, ...) — dependent: saas_event_properties(event)",
   "pack": "saas-analytics",
   "c": "saas"
  },
  {
   "n": "saas_event_stage",
   "a": "ev",
   "d": "lifecycle stage of an event (acquisition, activation, engagement, revenue, retention, referral) — dependent: saas_event_stage(event)",
   "pack": "saas-analytics",
   "c": "saas"
  },
  {
   "n": "saas_event_time",
   "a": "start_date,end_date,growth,profile",
   "d": "timestamp between two dates with growing volume (growth 2 = linear ramp, 1 = flat), weekday and hour-of-day shape (profile b2b or consumer), e.g. saas_event_time('2025-01-01', '2025-12-31')",
   "pack": "saas-analytics",
   "c": "saas"
  },
  {
   "n": "saas_experiment_name",
   "a": "",
   "d": "experiment key such as pricing_page_v2_202605",
   "pack": "saas-analytics",
   "s": [
    "onboarding_checklist_202606",
    "upgrade_modal_timing_202510",
    "upgrade_modal_timing_202607"
   ],
   "c": "saas"
  },
  {
   "n": "saas_feature",
   "a": "",
   "d": "product feature name (SSO, Webhooks, Automations, AI assistant, ...)",
   "pack": "saas-analytics",
   "s": [
    "Custom roles",
    "Custom fields",
    "AI assistant"
   ],
   "c": "saas"
  },
  {
   "n": "saas_industry",
   "a": "",
   "d": "customer industry for B2B accounts",
   "pack": "saas-analytics",
   "s": [
    "Manufacturing",
    "Software",
    "Manufacturing"
   ],
   "c": "saas"
  },
  {
   "n": "saas_mrr",
   "a": "pl,billing,seats",
   "d": "monthly recurring revenue = seat price x seats — dependent: saas_mrr(plan, billing_period, seats)",
   "pack": "saas-analytics",
   "c": "saas"
  },
  {
   "n": "saas_os",
   "a": "ua",
   "d": "operating system parsed from a user agent — dependent: saas_os(user_agent)",
   "pack": "saas-analytics",
   "c": "saas"
  },
  {
   "n": "saas_plan",
   "a": "",
   "d": "subscription plan (Free, Starter, Pro, Business, Enterprise), freemium-shaped mix",
   "pack": "saas-analytics",
   "s": [
    "Starter",
    "Free",
    "Free"
   ],
   "c": "saas"
  },
  {
   "n": "saas_platform",
   "a": "",
   "d": "client platform web, ios or android",
   "pack": "saas-analytics",
   "s": [
    "web",
    "ios",
    "ios"
   ],
   "c": "saas"
  },
  {
   "n": "saas_referrer",
   "a": "tsrc",
   "d": "referrer URL of a traffic source, NULL for direct and email — dependent: saas_referrer(traffic_source)",
   "pack": "saas-analytics",
   "c": "saas"
  },
  {
   "n": "saas_seat_price",
   "a": "pl,billing",
   "d": "list price per seat per month for a plan and billing period (annual is discounted) — dependent: saas_seat_price(plan, billing_period)",
   "pack": "saas-analytics",
   "c": "saas"
  },
  {
   "n": "saas_seats",
   "a": "pl",
   "d": "number of seats within the plan's range — dependent: saas_seats(plan)",
   "pack": "saas-analytics",
   "c": "saas"
  },
  {
   "n": "saas_traffic_source",
   "a": "",
   "d": "traffic source as \"source / medium\" (google / organic, (direct) / (none), ...), realistic mix",
   "pack": "saas-analytics",
   "s": [
    "google / organic",
    "newsletter / email",
    "linkedin / social"
   ],
   "c": "saas"
  },
  {
   "n": "saas_user_agent",
   "a": "",
   "d": "realistic browser user agent, weighted by device/OS/browser share",
   "pack": "saas-analytics",
   "s": [
    "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Mobile Safari/537.36",
    "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Mobile Safari/537.36",
    "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Mobile Safari/537.36"
   ],
   "c": "saas"
  },
  {
   "n": "saas_user_role",
   "a": "",
   "d": "workspace role (owner, admin, member, guest)",
   "pack": "saas-analytics",
   "s": [
    "member",
    "member",
    "member"
   ],
   "c": "saas"
  },
  {
   "n": "saas_utm_campaign",
   "a": "tsrc",
   "d": "utm_campaign for paid, email and video traffic (q3_webinar, spring_retargeting), NULL otherwise — dependent: saas_utm_campaign(traffic_source)",
   "pack": "saas-analytics",
   "c": "saas"
  },
  {
   "n": "saas_utm_medium",
   "a": "tsrc",
   "d": "utm_medium of a traffic source — dependent: saas_utm_medium(traffic_source)",
   "pack": "saas-analytics",
   "c": "saas"
  },
  {
   "n": "saas_utm_source",
   "a": "tsrc",
   "d": "utm_source of a traffic source — dependent: saas_utm_source(traffic_source)",
   "pack": "saas-analytics",
   "c": "saas"
  },
  {
   "n": "saas_variant",
   "a": "arms",
   "d": "A/B test arm: control or treatment (arms := 3 or 4 adds variant_b, variant_c), equal split",
   "pack": "saas-analytics",
   "c": "saas"
  },
  {
   "n": "job_title_composed",
   "a": "",
   "d": "composed job title: modifier + base role",
   "pack": "jobs-pro",
   "s": [
    "Retail Actress",
    "Program Anglesmith",
    "Insurance Actress"
   ],
   "c": "work"
  },
  {
   "n": "job_title_pro",
   "a": "",
   "d": "job title from 10k+ real-world titles",
   "pack": "jobs-pro",
   "s": [
    "Recoverer",
    "Cost Accountant",
    "Programming Jobs"
   ],
   "c": "work"
  }
 ]
};
