#!/usr/bin/env bash
# release.sh — build the rgen Linux release tarball into dist/.
#
#   ./release.sh              # build ../cuiqGEN/src, then package
#   ./release.sh --no-build   # package the binary that's already there
#
# Output: dist/rgen-cli-linux-x86_64.tar.gz — upload it as the GitHub release asset that
# install.sh and the Dockerfile download (releases/latest/download/...).
set -euo pipefail
cd "$(dirname "$0")"

SRC=${RGEN_SRC:-../cuiqGEN/src}
LIBDUCKDB=${LIBDUCKDB:-../vduckdb/src/thirdparty/libduckdb.so}
NAME=rgen-cli-linux-x86_64
OUT=dist/$NAME

[[ "${1:-}" == --no-build ]] || make -C "$SRC" build
[[ -x "$SRC/rgen" ]] || { echo "error: $SRC/rgen not found" >&2; exit 1; }
[[ -f "$LIBDUCKDB" ]] || { echo "error: libduckdb.so not found at $LIBDUCKDB" >&2; exit 1; }

rm -rf "$OUT" && mkdir -p "$OUT/bin"
cp "$SRC/rgen" "$OUT/bin/rgen"
cp "$LIBDUCKDB" "$OUT/bin/libduckdb.so"
python3 -c "import ctypes,sys; l=ctypes.CDLL(sys.argv[1]); l.duckdb_library_version.restype=ctypes.c_char_p; print(l.duckdb_library_version().decode())" \
  "$OUT/bin/libduckdb.so" > "$OUT/bin/DUCKDB_VERSION"

# Launcher: point the binary at the bundled libduckdb.so wherever the install lives (it is
# usually reached through a ~/.local/bin symlink, so resolve that first).
cat > "$OUT/rgen" <<'EOF'
#!/bin/sh
self=$(readlink -f "$0")
dir=$(dirname "$self")
LIBDUCKDB_DIR="$dir/bin" exec "$dir/bin/rgen" "$@"
EOF
chmod +x "$OUT/rgen" "$OUT/bin/rgen"

# Refresh the skill's provider reference from the binary being shipped.
{
  echo "# rgen providers"
  echo
  echo "Generated by \`rgen providers\` for rgen $(cat VERSION). Pass to \`-p\` without the \`rand_\` prefix;"
  echo "arguments in parentheses are optional unless shown in examples."
  echo
  echo '```'
  LIBDUCKDB_DIR="$OUT/bin" "$OUT/bin/rgen" providers | sed 's/\x1b\[[0-9;]*m//g' | sed '1{/^$/d}'
  echo '```'
} > skills/rgen/references/providers.md

cp -R skills examples install-skills.sh install-skills.ps1 README.md QUICK_REFERENCE.md LICENSE VERSION "$OUT/"

tar -C dist -czf "dist/$NAME.tar.gz" "$NAME"
rm -rf "$OUT"
ls -la "dist/$NAME.tar.gz"
sha256sum "dist/$NAME.tar.gz"
